export const FETCH_OWNERS_REQUEST = 'FETCH_OWNERS_REQUEST'
export const FETCH_OWNERS_SUCCESS = 'FETCH_OWNERS_SUCCESS'
export const FETCH_OWNERS_FAILURE = 'FETCH_OWNERS_FAILURE'

export const DELETE_OWNER = 'DELETE_OWNER'
export const ADD_EDIT_OWNER_SUCCESS = 'ADD_EDIT_OWNER_SUCCESS'

///// handle form
export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE'
export const HANDLE_CHECKBOX_CHANGE = 'HANDLE_CHECKBOX_CHANGE'
export const HANDLE_SWITCH_CHANGE = 'HANDLE_SWITCH_CHANGE'
export const HANDLE_FILE_UPLOAD_CHANGE = 'HANDLE_FILE_UPLOAD_CHANGE'

export const OPEN_ADD_EDIT_MODAL = 'OPEN_ADD_EDIT_MODAL'
export const CLOSE_ADD_EDIT_MODAL = 'CLOSE_ADD_EDIT_MODAL'

/// filters
export const HANDLE_FILTER_CHANGE = 'HANDLE_FILTER_CHANGE'
export const HANDLE_SORTING_CHANGE = 'HANDLE_SORTING_CHANGE'