// import axios from 'axios';
// axios.defaults.baseURL = '';

//All Default Text:
const configAppConst = {
    passwordTitle: 'Password',
    enterPasswordTitle: 'Please enter your password',
    closeTitle: 'Close',
    submitTitle: 'Submit',
    custNameTitle: 'Customer Name',
    paymentTitle: 'Payment',
    paymentAmountTitle: 'Payment Amount',
    balanceTitle: 'Balance',
    accBalanceTitle: 'Account Balance',
    invoiceTitle: 'Invoice No.',
    dateTitle: 'Date',
    amountTitle: 'Amount',
    paymentforTitle: 'Payment For',
    viewTitle: 'View',
    viewAllTitle: 'View All',
    payTitle: 'Pay',
    payAllTitle: 'Pay All',
    downloadTitle: 'Download',
    removeTitle: 'Remove',
    editTitle: 'Edit',
    clearBalTitle: 'Clear Balance',
    viewLessTitle: 'View Less',
    viewMoreTitle: 'View all Invoices',
    chargeTitle: '* Please note there will be a 4% surcharge fee for Credit Card payments',
    continueTitle: 'Continue',
    chooseAmountTitle: 'Choose the Amount',
    fullAmountTitle: 'Full Amount',
    partialAmountTitle: 'Partial Amount',
    selectPaymentETitle: 'Select at least one record for payment',
    paymentInfoTitle: 'Invoice Info',
    contactInfoTitle: 'Contact Info',
    creditCardTitle: 'Credit Card',
    modifyTitle: 'Modify',
    saveTitle: 'Save',
    sameContactInfoTitle: 'Same as Contact Info',
    nameTitle: 'Name',
    addressTitle: 'Address',
    cityTitle: 'City',
    stateTitle: 'State',
    zipTitle: 'Zip',
    backTitle: 'Back',
    reviewTitle: 'Review',
    payCreditTitle: 'paying with Credit Card Ending In',
    forTotalTitle: ' for a total of ',
    surchargeTitle: '* 4% surcharge fee of ',
    processPaymentTitle: 'Process Payment',
    paymentSuccessTitle: 'Payment Successfully Done !!',
    invoiceNumberTitle: 'Invoice Number',
    thanksTitle: 'Thank you for your payment',
    confirmNoTitle: 'Your confirmation number is ',
    businessTitle: 'We appreciate your business',
    doneTitle: 'Done',
}
export default configAppConst;